baseURL = "https://relaxed-kowalevski-5fd086.netlify.com/"
languageCode = "en"
title = "Jane's Grooming"
theme = "kiss-master"
copyright = ""
disqusShortname = "shortname"
googleAnalytics = ""
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "" # Author full name


[params.assets]
customCSS = ["css/custom.css"]

[params.info]


homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks



[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
